.TH MKLMKL 1 "2026-02-17" "1.5" "User Commands"
.SH NAME
mklmkl \- system utility tool
.SH SYNOPSIS
.B mklmkl
.RB [ info | ip | clean | du | help | version ]
.SH DESCRIPTION
.B mklmkl
is a lightweight system utility for Linux.
It can show system info, IP addresses, clean cache, and check directory size.
.SH COMMANDS
.TP
.B info
Show system information (hostname, memory, disk, etc.).
.TP
.B ip
Show local and public IP address.
.TP
.B clean
Clean user cache files.
.TP
.B du
Show directory size.
.TP
.B help
Show help message.
.TP
.B version
Show program version (1.5).
.SH AUTHOR
mklmkl
.SH LICENSE
MIT

